# Generated by Django 5.2.17 on 2026-08-13 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('funding_source', models.CharField(blank=True, max_length=200)),
                ('featured_image', models.ImageField(blank=True, upload_to='projects/')),
                ('beneficiaries', models.PositiveIntegerField(default=0)),
                ('impact_stories', models.TextField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
