# Generated by Django 5.2.17 on 2026-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('position', models.CharField(choices=[('executive_director', 'Executive Director'), ('programs_director', 'Programs Director'), ('advocacy_lead', 'Advocacy Lead'), ('operations_manager', 'Operations Manager'), ('finance_officer', 'Finance Officer'), ('communications_lead', 'Communications Lead'), ('project_manager', 'Project Manager'), ('youth_ambassador', 'Youth Ambassador'), ('board_member', 'Board Member'), ('advisor', 'Advisor'), ('other', 'Other')], default='other', max_length=50)),
                ('department', models.CharField(choices=[('executive', 'Executive'), ('programs', 'Programs'), ('advocacy', 'Advocacy'), ('operations', 'Operations'), ('finance', 'Finance'), ('communications', 'Communications'), ('projects', 'Projects'), ('youth', 'Youth Engagement'), ('board', 'Board of Directors'), ('advisory', 'Advisory Council')], default='programs', max_length=50)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
