# Generated by Django 5.2.17 on 2026-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['leader_type', 'order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='leader',
            name='department',
        ),
        migrations.AddField(
            model_name='leader',
            name='county',
            field=models.CharField(blank=True, help_text='County name (for county leaders)', max_length=100),
        ),
        migrations.AddField(
            model_name='leader',
            name='county_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='leader',
            name='leader_type',
            field=models.CharField(choices=[('nec', 'National Executive Council (NEC)'), ('county', 'County Leader'), ('board', 'Board of Directors'), ('advisory', 'Advisory Council'), ('staff', 'Staff Member')], default='nec', max_length=20),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(choices=[('national_chairperson', 'National Chairperson'), ('vice_chairperson_1', 'Vice Chairperson (1st)'), ('vice_chairperson_2', 'Vice Chairperson (2nd)'), ('secretary_general', 'Secretary General'), ('chief_finance_officer', 'Chief Finance Officer'), ('national_director_programs', 'National Director of Programs'), ('national_youth_leader', 'National Youth Leader'), ('empowerment_social_welfare', 'Director of Empowerment & Social Welfare'), ('national_women_rep', 'National Women Representative'), ('national_organizing_secretary', 'National Organizing Secretary'), ('board_member', 'Board Member'), ('advisor', 'Advisor'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
