# Generated by Django 5.2.17 on 2026-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_leader_options_remove_leader_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['leader_type', 'office', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='leader',
            name='office',
            field=models.CharField(choices=[('sg_office', "Secretary General's Office"), ('ceo_office', "CEO's Office"), ('vice_chair_1', 'Vice Chair 1 Office'), ('vice_chair_2', 'Vice Chair 2 Office'), ('cfo_office', "CFO's Office"), ('other', 'Other Office')], default='other', max_length=50),
        ),
    ]
