# Generated by Django 5.2.17 on 2026-09-03 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('county_chairperson', 'County Chairperson'), ('county_vice_chairperson', 'County Vice Chairperson'), ('county_secretary', 'County Secretary'), ('county_treasurer', 'County Treasurer'), ('ward_leader', 'Ward Leader'), ('national_official', 'National Official'), ('other', 'Other')], max_length=50)),
                ('county', models.CharField(blank=True, help_text='County for county positions', max_length=100)),
                ('ward', models.CharField(blank=True, help_text='Ward for ward positions', max_length=100)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('letter_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('letter_content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='appointments/letters/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appointments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
