# Generated by Django 5.2.17 on 2026-09-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='issuer',
            field=models.CharField(choices=[('chairperson', 'National Chairperson'), ('vice_chair_1', '1st Vice Chairperson'), ('vice_chair_2', '2nd Vice Chairperson'), ('secretary_general', 'Secretary General'), ('other', 'Other')], default='vice_chair_2', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='issuer_name',
            field=models.CharField(blank=True, help_text='Name of the person issuing the letter', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='issuer_title',
            field=models.CharField(blank=True, help_text='Title of the issuer', max_length=200),
        ),
    ]
