# Generated by Django 5.2.17 on 2026-09-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_issuer_appointment_issuer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='issuer_name',
            field=models.CharField(blank=True, default='Dericks Omondi', help_text='Name of the person issuing the letter', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='issuer_title',
            field=models.CharField(blank=True, default='2nd Vice Chairperson - Appointments', help_text='Title of the issuer', max_length=200),
        ),
    ]
