# Generated by Django 5.2.17 on 2026-08-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('civic_education', 'Civic Education'), ('youth_leadership', 'Youth Leadership'), ('advocacy', 'Advocacy'), ('community_engagement', 'Community Engagement'), ('entrepreneurship', 'Entrepreneurship'), ('digital_literacy', 'Digital Literacy'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('objective', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-graduation-cap', help_text='Font Awesome icon class', max_length=50)),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 months, 6 weeks', max_length=100)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('max_participants', models.PositiveIntegerField(default=50)),
                ('features', models.TextField(blank=True, help_text='List program features, one per line')),
                ('requirements', models.TextField(blank=True, help_text='List requirements, one per line')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, upload_to='programs/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
