# Generated by Django 5.2.17 on 2026-08-13 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('individual', 'Individual Member'), ('student', 'Student Member'), ('youth', 'Youth Member'), ('senior', 'Senior Member'), ('lifetime', 'Lifetime Member'), ('organizational', 'Organizational Member')], default='youth', max_length=20)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('membership_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('membership_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership_end_date', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(default='members/default.jpg', upload_to='members/')),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
    ]
