# Generated by Django 5.2.17 on 2026-09-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_county_name_alter_ward_code'),
        ('members', '0002_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='leadership_level',
            field=models.CharField(blank=True, help_text='e.g., County, Ward, National', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='leadership_position',
            field=models.CharField(blank=True, choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('secretary', 'Secretary'), ('organizing_secretary', 'Organizing Secretary'), ('treasurer', 'Treasurer'), ('youth_leader', 'Youth Leader'), ('women_rep', 'Women Representative'), ('pwd_leader', 'PWD Leader'), ('exofficial_male', 'Ex-official Member (Male)'), ('exofficial_female', 'Ex-official Member (Female)'), ('ward_leader', 'Ward Leader'), ('member', 'Member')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='position_type',
            field=models.CharField(blank=True, choices=[('county', 'County Position'), ('ward', 'Ward Position'), ('national', 'National Position')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
        migrations.AlterField(
            model_name='member',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
