# Generated by Django 5.2.17 on 2026-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_leader_member_leadership_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='leadership_position',
            field=models.CharField(blank=True, choices=[('county_chairperson', 'County Chairperson'), ('county_vice_chairperson', 'County Vice Chairperson'), ('county_secretary', 'County Secretary'), ('county_organizing_secretary', 'County Organizing Secretary'), ('county_treasurer', 'County Treasurer'), ('county_youth_leader', 'County Youth Leader'), ('county_women_rep', 'County Women Representative'), ('county_pwd_leader', 'County PWD Leader'), ('county_exofficial_male', 'County Ex-official Member (Male)'), ('county_exofficial_female', 'County Ex-official Member (Female)'), ('ward_chairperson', 'Ward Chairperson'), ('ward_vice_chairperson', 'Ward Vice Chairperson'), ('ward_secretary', 'Ward Secretary'), ('ward_organizing_secretary', 'Ward Organizing Secretary'), ('ward_treasurer', 'Ward Treasurer'), ('ward_youth_leader', 'Ward Youth Leader'), ('ward_women_rep', 'Ward Women Representative'), ('ward_pwd_leader', 'Ward PWD Leader'), ('national_chairperson', 'National Chairperson'), ('national_vice_chairperson', 'National Vice Chairperson'), ('national_secretary_general', 'Secretary General'), ('national_organizing_secretary', 'National Organizing Secretary'), ('national_treasurer', 'National Treasurer'), ('national_youth_leader', 'National Youth Leader'), ('national_women_rep', 'National Women Representative'), ('national_pwd_leader', 'National PWD Leader'), ('national_programs_director', 'National Programs Director')], max_length=50, null=True),
        ),
    ]
